import React, { useEffect, useRef } from 'react';
import { Layers, Sparkles, Download, Maximize2 } from 'lucide-react';
import { safeRenderMermaid, cleanMermaidSpec } from '../../utils/mermaidHelper.js';

interface ArchitectureViewerProps {
  diagram: string | null;
}

export const ArchitectureViewer: React.FC<ArchitectureViewerProps> = ({ diagram }) => {
  const containerRef = useRef<HTMLDivElement>(null);

  const defaultDiagram = `graph TD
    UserA["👤 User A (Alice)"] -->|WebSocket @mention| Gateway["⚡ Gateway & WebSocket Router"]
    UserB["👤 User B (Bob)"] -->|WebSocket @mention| Gateway
    Gateway --> Dispatcher["🧠 Multi-Agent Dispatcher"]

    subgraph Agents["Autonomous AI Agents"]
        Gemini["🤖 @gemini (Coder)"]
        Architect["📐 @architect (Design)"]
        Reviewer["🔍 @reviewer (Audit)"]
        Debugger["🐛 @debugger (Fix)"]
    end

    Dispatcher --> Agents
    Agents -->|Tool Executions| FileStore["📁 Shared Filesystem & GitHub Context"]
    FileStore -->|Realtime Diff Broadcast| Gateway`;

  const activeDiagram = diagram || defaultDiagram;

  useEffect(() => {
    if (containerRef.current) {
      safeRenderMermaid(containerRef.current, activeDiagram, 'architecture-panel');
    }
  }, [activeDiagram]);

  return (
    <div className="flex-1 flex flex-col h-full bg-dark-950/90 overflow-hidden">
      {/* Header */}
      <div className="h-10 px-4 border-b border-slate-800 bg-dark-900 flex items-center justify-between text-xs select-none">
        <div className="flex items-center space-x-2">
          <Layers className="w-4 h-4 text-cyan-400" />
          <span className="font-semibold text-slate-200">System Architecture & Mermaid Inspector</span>
        </div>
        <span className="text-[10px] font-mono text-cyan-400 bg-cyan-500/10 px-2 py-0.5 rounded border border-cyan-500/20">
          Generated by @architect
        </span>
      </div>

      {/* Render Canvas */}
      <div className="flex-1 p-6 overflow-auto flex items-center justify-center">
        <div ref={containerRef} className="max-w-full" />
      </div>

      {/* Footer Code Source */}
      <div className="p-3 bg-dark-900 border-t border-slate-800 font-mono text-[10px] text-slate-400 max-h-32 overflow-y-auto">
        <div className="text-[10px] uppercase font-semibold text-slate-400 mb-1">Mermaid Source Spec</div>
        <pre className="text-slate-300 whitespace-pre-wrap">{activeDiagram}</pre>
      </div>
    </div>
  );
};
