import WebSocket from 'ws';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const WS_URL = 'ws://localhost:3001/ws';
const API_URL = 'http://localhost:3001/api/config/apikey';

async function runMultiAgentTest() {
  console.log('🚀 Testing Multi-Agent Tagging (@architect + @gemini + @reviewer)...\n');

  const apiKey = process.env.GEMINI_API_KEY || 'AIzaSyC9ud8bVb2bRGMzWCrIJNoPjWY7SyG7Gq4';
  await fetch(API_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ apiKey })
  });

  const ws = new WebSocket(WS_URL);

  ws.on('open', () => {
    ws.send(JSON.stringify({
      type: 'JOIN_ROOM',
      payload: {
        roomId: 'room-dev-1',
        user: { id: 'user-lead-1', name: 'Alice (Tech Lead)', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice', role: 'human' }
      }
    }));

    const responsesReceived = new Map<string, any>();

    ws.on('message', (raw) => {
      try {
        const packet = JSON.parse(raw.toString());
        if (packet.type === 'AGENT_STREAM_UPDATE' && packet.payload?.message?.isStreaming === false) {
          const msg = packet.payload.message;
          console.log(`✨ [MULTI-AGENT RESPONSE RECEIVED] ${msg.sender.handle} (${msg.sender.name})`);
          console.log(`Content:\n${msg.content.slice(0, 250)}...\n`);
          if (msg.architectureDiagram) {
            console.log(`📐 Mermaid Architecture Diagram Generated by ${msg.sender.handle}!`);
          }
          responsesReceived.set(msg.sender.handle, msg);

          if (responsesReceived.size >= 2) {
            console.log('🎉 SUCCESS: Multi-agent tagging test complete! Both agents responded cleanly in parallel.');
            ws.close();
            process.exit(0);
          }
        }
      } catch (e) {}
    });

    console.log('💬 Sending prompt tagging both @architect and @gemini...');
    ws.send(JSON.stringify({
      type: 'SEND_MESSAGE',
      payload: {
        message: {
          id: `msg-multi-${Date.now()}`,
          roomId: 'room-dev-1',
          sender: { id: 'user-lead-1', name: 'Alice (Tech Lead)', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice', role: 'human' },
          content: '@architect generate a system architecture diagram for a user auth service, and @gemini create auth_service.py with password hashing and JWT token logic.',
          timestamp: new Date().toISOString(),
          mentions: ['@architect', '@gemini']
        }
      }
    }));
  });
}

runMultiAgentTest().catch(console.error);
